### PR TITLE
Spelling Mistake & Hyperlink Correction, Tutorials Title Update, Document Reorganization Suggestion

### PR DESCRIPTION
**Pull request by smmehrab**
This is my first PR to any OS project. Thank you!

### CODE REVIEW

**Comment by smmehrab** [comment]
About Document Reorganization Suggestion

Firstly, pardon me, if I am causing too much chaos in it. But I am just thinking out loud as I am a first timer too.

Firstly, I felt lost in the document as there was no "Getting Started" portion. There were just too many options.

Secondly, Projects & Contests was the priority for me, which I found at the end of the document. I mean, at the bottom of the content list.

Thirdly, after I have read through it, I didn't think the "Download", "How it Works" details were necessary for this document as I am not here to learn about those tools or contests. I am here to get a simple yet helpful pathways to my future open source contribution (first open source contribution - for me). 

That was my thought about it. Just an opinion.

**Comment by ankitdobhal** [comment]
> About **Document Reorganization Suggestion** Commit
> 
> Firstly, pardon me, if I am causing too much chaos in it. But I am just thinking out loud as I am a first timer too.
> 
> Firstly, I felt lost in the document as there was no "Getting Started" portion. There were just too many options.
> 
> Secondly, Projects & Contests was the priority for me, which I found at the end of the document. I mean, at the bottom of the content list.
> 
> Thirdly, after I have read through it, I didn't think the "Download", "How it Works" details were necessary for this document as I am not here to learn about those tools or contests. I am here to get a simple yet helpful pathways to my future open source contribution (first open source contribution - for me).
> 
> That was my thought about it. Just an opinion.

> Firstly its a Good Suggestion @smmehrab  .

> Actually We are trying to provide every type resources for beginner's ,intermediate every type.

 And as a contributor from learning experience its important to participate such kind of big contest it 
 most time helps beginner's to be familiar with actual contribution world. 

> And for that we created sections for all type of contest for the detailed description  so if newbies 
  comes into any kind of contest so this Repo can help them . 
> But we appreciate your suggestion for getting-started and the second about download portions.
  Its a open for all type contributions , but before doing any changes we want you to update your PR 
  again  , for the more resources but if you think you can add any good section , we will welcome 
  your contributions.
Thanks @smmehrab

**Comment by smmehrab** [comment]
Okay, now I understand better. Thank you.

May I add the getting started part and keep the Contest details, Tools details part unchanged?

**Comment by ankitdobhal** [comment]
> Okay, now I understand better. Thank you.
> 
> May I add the getting started part and keep the Contest details, Tools details part unchanged?

Yes sure add and for tools and version control section we will update it with descriptions as what they are and how to use them with some resources.

**Comment by smmehrab** [comment]
Okay, I think I have just done that on previous commit. Would you please, give it a check?

**Comment by ankitdobhal** [comment]
> Okay, I think I have just done that on previous commit. Would you please, give it a check?

@smmehrab do more contribution with us.
Thanks

**Pull request merged**
